language: node_js
node_js: "10"
php: 7.1
jobs:
  include:
    - stage: test
      name: 'Unit on Node.js8 / PHP5.3'
      node_js: "8"
      php: 5.6
      install: npm ci && composer install
      script: npm test
    - stage: test
      name: 'Unit on Node.js10 / PHP7.0'
      install: npm ci && composer install
      script: npm test
    - stage: test
      name: 'Lint'
      install: npm ci
      script: npm run lint
    - stage: test
      name: 'Coverage'
      install: npm ci
      script: npm run coveralls
    - stage: release
      if: branch = master
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        install: npm ci
        script: npx semantic-release
